import { PrismaClient } from '@prisma/client';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
const prisma = new PrismaClient();

export default function Home() {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[] }[]
  // >([]);
  const [products, setProducts] = useState<{ id: string; name: string }[]>([]);

  useEffect(() => {
    fetch('/api/get-products')
      .then((res) => res.json())
      .then((data) => {
        if (data.items) {
          setProducts(data.items);
        }
      })
      .catch((error) => console.log(error));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1>{time}</h1> */}
        <h1>
          <Link href="/ssg">ssg</Link>
        </h1>
        <h1>
          <Link href="/isr">isr</Link>
        </h1>
        <p>Products Listd</p>
        {products &&
          products?.map((item) => <div key={item.id}>{item.name}</div>)}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const products = await prisma.products.findMany();
  return {
    props: { products },
  };
}
