import Head from 'next/head';
import Link from 'next/link';

export default function Home({ time }: { time: string }) {
  const handleClick = () => {
    fetch('/api/add-item?name=Jacket')
      .then((res) => res.json())
      .then((data) => alert(data.message));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{time}</h1>
        <h1>
          <Link href="/ssg">ssg</Link>
        </h1>
        <h1>
          <Link href="/isr">isr</Link>
        </h1>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  console.log('server');
  return {
    props: { time: new Date().toISOString() },
  };
}
